# Generated by Django 5.2.9 on 2026-03-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedevice',
            name='activation_code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
